### ISSUE TITLE
Animation inside UITableView

### ISSUE THREAD

**Issue by iSpartak** [MatiBot/MBCircularProgressBar#20]
Seems animation doesn't work if I place the instance of progress bar in custom cell and call setValue with animationWithDuration

Edit: it works when scrolling but not sure how to make it visible in first load. Anyhow, I think this can be closed as it is not this code issue. Thank you!

**Comment by Werbelow** [comment]
I am also seeing this bug, I don't see it on scroll ether though.

**Comment by scottpchow23** [comment]
A really hacky way I found to work around it was to set off the run animation with a hard coded delay, as it seems that the animation fails to run correctly in the contexts of table views (your case) and collection views (my case).

**Comment by jakehoskins** [comment]
I have the same issue in a UIScrollView but that hack didn't work for me

**Comment by scottpchow23** [comment]
Could you show me how you are doing the hard coded delay? I'm using NSNotificationCenter with a post notification that the circular progress bars are listening to.

**Comment by jakehoskins** [comment]
```
    [UIView animateWithDuration:3 delay:0.5 options:UIViewAnimationOptionCurveLinear animations:^{
        circular.value =55.f;
    } completion:nil];
```

**Comment by scottpchow23** [comment]
Yeah, that won't work because the issue is that the animation seems to go off before the view itself finishes loading. You need to create an NSNotification post to which your progress bars will listen to. When they "hear" the notification, they should then call the animate function. The key thing here is to delay the timing of the notification post (I used .5 as well) which should allow the entire layout routine to finish before the animation.

**Comment by NishaParmar** [comment]
Same not working  animation in tableview found any way?

**Comment by AurelTyson** [comment]
Hi,
I get it working in a UICollectionViewCell by doing this :
```swift
DispatchQueue.main.async {
    UIView.animate(withDuration: 1, delay: 0, options: [], animations: {
        circularProgress.value = CGFloat(50)
    }, completion: nil)
}
```
